# Core API Endpoints
ENSEMBLE_IDS_ENDPOINT = "/coreAPI/ensembleids"
IMS_ENDPOINT = "/coreAPI/imids"
CONTEXT_MAP_ENDPOINT = "/coreAPI/contextmap"
VS30_MAP_ENDPOINT = "/coreAPI/vs30map"
STATION_ENDPOINT = "/coreAPI/station"
HAZARD_ENDPOINT = "/coreAPI/hazard"
HAZARD_NZ11705_ENDPOINT = "/coreAPI/hazard/nz1170p5"
HAZARD_NZ11705_SOIL_CLASS_ENDPOINT = "/coreAPI/hazard/nz1170p5/soil_class"
HAZARD_NZ11705_DEFAULT_PARAMS_ENDPOINT = "/coreAPI/hazard/nz1170p5/default"
HAZARD_DISAGG_ENDPOINT = "/coreAPI/disagg"
HAZARD_UHS_ENDPOINT = "/coreAPI/uhs"
HAZARD_UHS_NZ11705_ENDPOINT = "/coreAPI/uhs/nz1170p5"
GMS_ENDPOINT = "/coreAPI/gms/ensemble_gms"
GMS_DEFAULT_IM_WEIGHTS_ENDPOINT = "/coreAPI/gms/default_im_weights"
GMS_DEFAULT_CAUSAL_PARAMS_ENDPOINT = "/coreAPI/gms/default_causal_params"
GMS_DATASETS_ENDPOINT = "/coreAPI/gms/ensemble_gms/datasets"
GMS_IMS_ENDPOINT_ENDPOINT = "/coreAPI/gms/ensemble_gms/ims"

# Download Endpoints
HAZARD_CURVE_DOWNLOAD_ENDPOINT = "/coreAPI/hazard_download"
HAZARD_DISAGG_DOWNLOAD_ENDPOINT = "/coreAPI/disagg_download"
HAZARD_UHS_DOWNLOAD_ENDPOINT = "/coreAPI/uhs_download"
GMS_DOWNLOAD_ENDPOINT = "/coreAPI/gms_download"
