# Core API Endpoints
CORE_API_ENSEMBLE_IDS_ENDPOINT = "/coreAPI/ensembleids"
CORE_API_IMS_ENDPOINT = "/coreAPI/imids"
CORE_API_CONTEXT_MAP_ENDPOINT = "/coreAPI/contextmap"
CORE_API_VS30_MAP_ENDPOINT = "/coreAPI/vs30map"
CORE_API_STATION_ENDPOINT = "/coreAPI/station"
CORE_API_HAZARD_ENDPOINT = "/coreAPI/hazard"
CORE_API_HAZARD_NZ11705_ENDPOINT = "/coreAPI/hazard/nz1170p5"
CORE_API_HAZARD_NZ11705_SOIL_CLASS_ENDPOINT = "/coreAPI/hazard/nz1170p5/soil_class"
CORE_API_HAZARD_NZ11705_DEFAULT_PARAMS_ENDPOINT = "/coreAPI/hazard/nz1170p5/default"
CORE_API_HAZARD_DISAGG_ENDPOINT = "/coreAPI/disagg"
CORE_API_HAZARD_UHS_ENDPOINT = "/coreAPI/uhs"
CORE_API_HAZARD_UHS_NZ11705_ENDPOINT = "/coreAPI/uhs/nz1170p5"
CORE_API_GMS_ENDPOINT = "/coreAPI/gms/ensemble_gms"
CORE_API_GMS_DEFAULT_IM_WEIGHTS_ENDPOINT = "/coreAPI/gms/default_im_weights"
CORE_API_GMS_DEFAULT_CAUSAL_PARAMS_ENDPOINT = "/coreAPI/gms/default_causal_params"
CORE_API_GMS_DATASETS_ENDPOINT = "/coreAPI/gms/ensemble_gms/datasets"
CORE_API_GMS_IMS_ENDPOINT_ENDPOINT = "/coreAPI/gms/ensemble_gms/ims"

# Download Endpoints
CORE_API_HAZARD_CURVE_DOWNLOAD_ENDPOINT = "/coreAPI/hazard_download"
CORE_API_HAZARD_DISAGG_DOWNLOAD_ENDPOINT = "/coreAPI/disagg_download"
CORE_API_HAZARD_UHS_DOWNLOAD_ENDPOINT = "/coreAPI/uhs_download"
CORE_API_GMS_DOWNLOAD_ENDPOINT = "/coreAPI/gms_download"

# Project API Endpoints
